import "../styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import { PersistGate } from "redux-persist/integration/react";
import store, { persistStorage } from "../store";
import { Provider } from "react-redux";
import React, { FC, ReactNode } from "react";
require("@solana/wallet-adapter-react-ui/styles.css");

import MainLayout from "../components/Main-Layout";
import AutoConnectWalletProvider from "../contexts/AutoConnectWalletContext";

export default function App({ Component, pageProps, ...props }: AppProps) {
  return (
    <>
      <Head>
        <title>Solana Coding Camp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AutoConnectWalletProvider>
          <Provider store={store}>
            <PersistGate loading={null} persistor={persistStorage}>
              <MainLayout pageProps={pageProps} Component={Component} {...props}>
                    <Component {...pageProps} />
              </MainLayout>
            </PersistGate>
          </Provider>
      </AutoConnectWalletProvider>
    </>
  );
}
